### ISSUE TITLE
get_bcaddress_version throws a casting error

### ISSUE THREAD

**Issue by ahmedbodi** [simplecrypto/cryptokit#10]
```
2015-08-12 18:29:44,066 [StratumServer_STRAT_SCRYPT] [DEBUG] Data {u'params': [u' 1H62sfHUNArwqoSooT58UVLvHcxep6L5dM.2', u'X'], u'id': 203615, u'method': u'mining.authorize'} recieved on client 71c5c504
2015-08-12 18:29:44,066 [StratumServer_STRAT_SCRYPT] [INFO] Authentication request from 199.36.88.176 for username  1H62sfHUNArwqoSooT58UVLvHcxep6L5dM.2
2015-08-12 18:29:44,066 [StratumServer_STRAT_SCRYPT] [DEBUG] Registering worker name 2
Python int too large to convert to C long
 1H62sfHUNArwqoSooT58UVLvHcxep6L5dM Has Address Version: False
2015-08-12 18:29:44,067 [StratumServer_STRAT_SCRYPT] [DEBUG] Invalid address passed in, checking aliases against 1h62sfhunarwqosoot58uvlvhcxep6l5dm
2015-08-12 18:29:44,067 [StratumServer_STRAT_SCRYPT] [DEBUG] Falling back to donate key donate
2015-08-12 18:29:44,067 [StratumServer_STRAT_SCRYPT] [DEBUG] success response: {'error': None, 'id': 203615, 'result': True}
2015-08-12 18:29:44,067 [StratumServer_STRAT_SCRYPT] [DEBUG] Sending job id 02000000 to worker donate.2
2015-08-12 18:29:44,174 [StratumServer_STRAT_SCRYPT] [DEBUG] Data {u'params': [], u'id': 203616, u'method': u'mining.extranonce.subscribe'} recieved on client 71c5c504
2015-08-12 18:29:44,175 [StratumServer_STRAT_SCRYPT] [DEBUG] success response: {'error': None, 'id': 203616, 'result': True}
```
```
Traceback (most recent call last):
  File "/home/ahmed/powerpool/powerpool/server.py", line 24, in convert_username
    version = get_bcaddress_version(username)
  File "build/bdist.linux-x86_64/egg/cryptokit/base58.py", line 88, in get_bcaddress_version
    return _parse_address(str_address)[0]
  File "build/bdist.linux-x86_64/egg/cryptokit/base58.py", line 71, in _parse_address
    raw = b58decode(str_address, 25)
  File "build/bdist.linux-x86_64/egg/cryptokit/base58.py", line 54, in b58decode
    result = chr(long_value) + result
OverflowError: Python int too large to convert to C long

 1H62sfHUNArwqoSooT58UVLvHcxep6L5dM Has Address Version: False
```
Thats the output from powerpool. will fetch a traceback now

**Comment by ahmedbodi** [comment]
Figured out the issue. somehow theres 2 extra spaces appended at the start of the worker name although it isnt like that on my miner. added .strip() to the area where the address is checked and now its all fine

**Comment by icook** [comment]
Interesting, that makes perfect sense. It makes more sense to run strip in powerpool since it's really not the job of the library. 

https://github.com/simplecrypto/powerpool/commit/c1c58827f54f1c49051dde40138191efbfef7cf5
